### ISSUE TITLE
关于显示日期与实际日期不一致的问题

### ISSUE THREAD

**Issue by babbittry** [overmind1980/lovestory#2]
Oeasy老师您好，我发现一个问题就是我在日历查询2014年2月9日到2018年10月29日之间日期间隔1723天，但是在网页http://oeasy.org/love/     上显示日期间隔了1695天，两者不一致，请问这是什么问题？

**Comment by babbittry** [comment]
老师我查了Javascript官方文档之后知道了。

在 `Date` 的章节中说：

>JavaScript counts months from 0 to 11.
  January is 0. December is 11.

所以 `2014,  2, 9 `表示的是2014年1月9日

**Comment by overmind1980** [comment]
感谢您的发现！
